//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Nintendulator.rc
//
#define IDC_MYICON                      2
#define IDD_ABOUTBOX                    101
#define IDS_APP_TITLE                   102
#define IDM_EXIT                        103
#define IDI_NINTENDULATOR               104
#define IDI_SMALL                       105
#define IDC_NINTENDULATOR               106
#define IDR_NINTENDULATOR               107
#define IDS_NINTENDULATOR               108
#define IDD_PALETTE                     128
#define IDD_PATTERN                     129
#define IDD_DEBUGGER_PALETTE            130
#define IDD_DEBUGGER_PATTERN            131
#define IDD_DEBUGGER_NAME               132
#define IDD_DEBUGGER                    133
#define IDD_CONTROLLERS                 134
#define IDD_STDPORT_ZAPPER              135
#define IDD_STDPORT_STDCONTROLLER       136
#define IDD_STDPORT_ARKANOIDPADDLE      137
#define IDD_STDPORT_POWERPAD            138
#define IDD_STDPORT_FOURSCORE           139
#define IDD_EXPPORT_FAMI4PLAY           140
#define IDB_BITMAP1                     140
#define IDD_DEBUGGER_TRACE              141
#define ID_GAME                         141
#define IDD_DEBUGGER_REGISTERS          142
#define ID_CPU_AUTORUN                  142
#define ID_FILE_AUTORUN                 142
#define IDD_DEBUGGER_DUMPS              143
#define IDD_EXPPORT_ARKANOIDPADDLE      144
#define IDD_KEYCONFIG                   145
#define IDD_EXPPORT_FAMTRAIN            146
#define IDD_DEBUG                       147
#define IDD_INESHEADER                  148
#define IDC_DUMP_PPU_MEM                1001
#define IDC_START_LOGGING               1002
#define IDC_STOP_LOGGING                1003
#define IDC_IRQBUTTON                   1004
#define IDC_CONT_SPORT1                 1005
#define IDC_CONT_SPORT2                 1006
#define IDC_CONT_SPORT3                 1007
#define IDC_CONT_SPORT4                 1008
#define IDC_CONT_CPORT1                 1009
#define IDC_CONT_CPORT2                 1010
#define IDC_CONT_CPORT3                 1011
#define IDC_CONT_CPORT4                 1012
#define IDC_CONT_SEXPPORT               1013
#define IDC_CONT_CEXPPORT               1014
#define IDC_CONT_D0                     1015
#define IDC_CONT_D1                     1016
#define IDC_CONT_D2                     1017
#define IDC_CONT_D3                     1018
#define IDC_CONT_D4                     1019
#define IDC_CONT_D5                     1020
#define IDC_CONT_D6                     1021
#define IDC_CONT_D7                     1022
#define IDC_CONT_D8                     1023
#define IDC_CONT_D9                     1024
#define IDC_CONT_D10                    1025
#define IDC_CONT_D11                    1026
#define IDC_CONT_D12                    1027
#define IDC_CONT_D13                    1028
#define IDC_CONT_D14                    1029
#define IDC_CONT_D15                    1030
#define IDC_CONT_K0                     1031
#define IDC_CONT_K1                     1032
#define IDC_CONT_K2                     1033
#define IDC_CONT_K3                     1034
#define IDC_CONT_K4                     1035
#define IDC_CONT_K5                     1036
#define IDC_CONT_K6                     1037
#define IDC_CONT_K7                     1038
#define IDC_CONT_K8                     1039
#define IDC_CONT_K9                     1040
#define IDC_CONT_K10                    1041
#define IDC_CONT_K11                    1042
#define IDC_CONT_K12                    1043
#define IDC_CONT_K13                    1044
#define IDC_CONT_K14                    1045
#define IDC_CONT_K15                    1046
#define IDC_CONT_FLIP                   1055
#define IDC_DEBUGTEXT                   1062
#define IDC_INESBATT                    1063
#define IDC_INESTRAIN                   1064
#define IDC_INES4SCR                    1065
#define IDC_INESHORIZ                   1066
#define IDC_INESVERT                    1067
#define IDC_INESVS                      1068
#define IDC_INESPC10                    1069
#define IDC_INESPRG                     1070
#define IDC_INESCHR                     1071
#define IDC_INESMAP                     1072
#define IDC_INESNAME                    1075
#define IDM_ABOUT                       32770
#define ID_FILE_OPEN                    32771
#define ID_FILE_CLOSE                   32772
#define ID_CPU_RUN                      32773
#define ID_CPU_STOP                     32774
#define ID_CPU_SAVESTATE                32775
#define ID_CPU_LOADSTATE                32776
#define ID_CPU_PREVSTATE                32777
#define ID_CPU_NEXTSTATE                32778
#define ID_CPU_INCREMENTAL              32779
#define ID_CPU_HARDRESET                32780
#define ID_CPU_SOFTRESET                32781
#define ID_CPU_GAMEGENIE                32782
#define ID_PPU_FRAMESKIP_AUTO           32783
#define ID_PPU_FRAMESKIP_0              32784
#define ID_PPU_FRAMESKIP_1              32785
#define ID_PPU_FRAMESKIP_2              32786
#define ID_PPU_FRAMESKIP_3              32787
#define ID_PPU_FRAMESKIP_4              32788
#define ID_PPU_FRAMESKIP_5              32789
#define ID_PPU_FRAMESKIP_6              32790
#define ID_PPU_FRAMESKIP_7              32791
#define ID_PPU_FRAMESKIP_8              32792
#define ID_PPU_FRAMESKIP_9              32793
#define ID_PPU_SIZE_1X                  32794
#define ID_PPU_SIZE_2X                  32795
#define ID_PPU_SIZE_3X                  32796
#define ID_PPU_SIZE_4X                  32797
#define ID_PPU_SIZE_KEEPASPECTRATIO     32798
#define ID_PPU_MODE_NTSC                32799
#define ID_PPU_MODE_PAL                 32800
#define ID_INPUT_SETUP                  32801
#define ID_SOUND_ENABLED                32802
#define ID_DEBUG_LEVEL1                 32803
#define ID_DEBUG_LEVEL2                 32804
#define ID_DEBUG_LEVEL3                 32805
#define ID_DEBUG_LEVEL4                 32806
#define ID_CPU_STEP                     32807
#define ID_MISC_STARTAVICAPTURE         32809
#define ID_MISC_STOPAVICAPTURE          32810
#define ID_MISC_PLAYMOVIE               32811
#define ID_MISC_STOPMOVIE               32812
#define ID_MISC_RECORDMOVIE             32813
#define ID_DEBUG_STATWND                32814
#define ID_FILE_HEADER                  32815
#define ID_MISC_RECORDSTATE             32816
#define ID_MISC_RESUMEMOVIE             32817
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
